[package]
name = "azuma_backend"
version = "0.0.0"
authors = ["okrplay <32576280+okrplay@users.noreply.github.com>"]
edition = "2018"

[dependencies]
actix-web = "0.7"
lazy_static = "1.3"
mongodb = "0.3"