[package]
name = "azuma_backend"
version = "0.0.1"
authors = ["okrplay <32576280+okrplay@users.noreply.github.com>"]
edition = "2018"

[dependencies]
actix-web = "0.7"
bcrypt = "0.4"
bson = "0.13"
lazy_static = "1.3"
mongodb = "0.3"
rsgen = "0.2.0"
serde = "1.0"
serde_derive = "1.0"